# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.10
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      
    - name: Lint
      run: pnpm lint
      
    - name: Build
      run: pnpm build
      
    - name: Upload web build artifact
      if: success() && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: apps/web/.next/
        retention-days: 7
        
    - name: Upload packages artifacts
      if: success() && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: packages-dist
        path: |
          packages/ui/dist/
          packages/utils/dist/
        retention-days: 7
